annotations_path: ./data/annotations_phoenix/train_corpus.csv
batch_size: 4
bidirectional: false
curriculum_overlap_ratio: 0.3
curriculum_stages: 4
curriculum_warmup_epochs: 5
data_dir: ./data/phoenix_train
device: cuda
dropout: 0.1
experiment_name: optuned-jsons
gradient_clip_norm: 1.0
hidden_size: 768
input_size: 345
learning_rate: 6.039e-05
max_annotation_length: 25
max_sequence_length: 224
model_save_path: ./loss14/lstm_sign2gloss.pth
num_epochs: 50
num_layers: 1
patience: 8
project_name: sign-language-lstm
use_curriculum_learning: true
vocab_path: ./vocab.pkl
weight_decay: 3.877e-05
